export const types = {
  REQUEST_POKEMON_LIST: 'REQUEST_POKEMON_LIST',
  LOAD_POKEMON_LIST_OK: 'LOAD_POKEMON_LIST_OK',
  LOAD_POKEMON_LIST_FAIL: 'LOAD_POKEMON_LIST_FAIL',

  REQUEST_POKEMON_ITEM: 'REQUEST_POKEMON_ITEM',
  LOAD_POKEMON_ITEM_OK: 'LOAD_POKEMON_ITEM_OK',
  LOAD_POKEMON_ITEM_FAIL: 'LOAD_POKEMON_ITEM_FAIL',

  REQUEST_POKEMON_PAGE: 'REQUEST_POKEMON_PAGE',
  LOAD_POKEMON_PAGE_OK: 'LOAD_POKEMON_PAGE_OK',
  LOAD_POKEMON_PAGE_FAIL: 'LOAD_POKEMON_PAGE_FAIL',

  FILTER_POKE: 'FILTER_POKE',
  PAGINATION: 'PAGINATION'
}
